### PR TITLE
Update DAOS VOL for HDF5 1.13 and DAOS changes

### PR DESCRIPTION
**Pull request by jhendersonHDF**

### CODE REVIEW

File: src/daos_vol.c [hunk 1]
```diff
@@ -1864,6 +1870,35 @@ H5_daos_get_conn_cls(void *item, H5VL_get_conn_lvl_t H5VL_DAOS_UNUSED lvl,
...
+H5_daos_get_cap_flags(const void H5VL_DAOS_UNUSED *info, unsigned *cap_flags)
+{
+    herr_t ret_value = SUCCEED;
+
+    H5_daos_inc_api_cnt();
+
+    if(!cap_flags)
+        D_GOTO_ERROR(H5E_ARGS, H5E_BADVALUE, FAIL, "invalid cap_flags parameter");
+
+    H5_DAOS_MAKE_ASYNC_PROGRESS(FAIL);
```
Comment (soumagne) [inline src/daos_vol.c:1893]: would not hurt to have a one line comment about what that means

Comment (soumagne) [reply src/daos_vol.c:1893]: hmm alright... still kind of clunky here but ok I guess...

Comment (soumagne) [reply src/daos_vol.c:1893]: Let's leave it like that for now but maybe put a todo note. I feel like we should review where that gets done in general, I don't think we should allow for progress to be made everywhere otherwise this kind of routine might take longer whereas it is supposed to be immediate.

Comment (fortnern) [reply src/daos_vol.c:1893]: Well it is still immediate in the sense that it never blocks. It just might take an order or two magnitude more CPU time than expected.

File: src/daos_vol_file.c [hunk 2]
```diff
@@ -2990,8 +2986,9 @@ H5_daos_file_delete_status_bcast_comp_cb(tse_task_t *task, void H5VL_DAOS_UNUSED
     /* Handle errors in bcast task.  Only record error in udata->req_status if
      * it does not already contain an error (it could contain an error if
      * another task this task is not dependent on also failed). */
-    if(task->dt_result < -H5_DAOS_PRE_ERROR
-            && udata->req->status >= -H5_DAOS_SHORT_CIRCUIT) {
+    if((task->dt_result < -H5_DAOS_PRE_ERROR
+            && udata->req->status >= -H5_DAOS_SHORT_CIRCUIT) ||
+            ( *((herr_t *)udata->buffer) < 0)) {
```
Comment (fortnern) [inline src/daos_vol_file.c:2991]: My preference would be for this check to be in a different block, this is sort of a one-off change to boilerplate code, and a more specific error message for the case where the lead rank failed would be helpful anyways

Comment (fortnern) [reply src/daos_vol_file.c:2991]: Also I think "task->dt_result" would have the wrong value in that case

**Comment by mchaarawi** [comment]
I can't get this PR to build:

`[  1%] Building C object src/CMakeFiles/hdf5_vol_daos.dir/daos_vol.c.o
In file included from /home/mschaara/source/vol-daos/src/daos_vol.c:16:0:
/home/mschaara/source/vol-daos/src/daos_vol.h:1145:56: error: unknown type name ‘H5VL_file_get_args_t’
 H5VL_DAOS_PRIVATE herr_t H5_daos_file_get(void *_item, H5VL_file_get_args_t *get_args, hid_t dxpl_id,
                                                        ^
/home/mschaara/source/vol-daos/src/daos_vol.h:1147:60: error: unknown type name ‘H5VL_file_specific_args_t’
 H5VL_DAOS_PRIVATE herr_t H5_daos_file_specific(void *item, H5VL_file_specific_args_t *specific_args,
                                                            ^
...
`

**Comment by jhendersonHDF** [comment]
> I can't get this PR to build:
> 
> `[ 1%] Building C object src/CMakeFiles/hdf5_vol_daos.dir/daos_vol.c.o In file included from /home/mschaara/source/vol-daos/src/daos_vol.c:16:0: /home/mschaara/source/vol-daos/src/daos_vol.h:1145:56: error: unknown type name ‘H5VL_file_get_args_t’ H5VL_DAOS_PRIVATE herr_t H5_daos_file_get(void *_item, H5VL_file_get_args_t *get_args, hid_t dxpl_id, ^ /home/mschaara/source/vol-daos/src/daos_vol.h:1147:60: error: unknown type name ‘H5VL_file_specific_args_t’ H5VL_DAOS_PRIVATE herr_t H5_daos_file_specific(void *item, H5VL_file_specific_args_t *specific_args, ^ ... `

Are you using the latest develop? H5VL_file_get_args_t, etc. were introduced a while ago in the develop branch.

**Comment by mchaarawi** [comment]
> > I can't get this PR to build:
> > `[ 1%] Building C object src/CMakeFiles/hdf5_vol_daos.dir/daos_vol.c.o In file included from /home/mschaara/source/vol-daos/src/daos_vol.c:16:0: /home/mschaara/source/vol-daos/src/daos_vol.h:1145:56: error: unknown type name ‘H5VL_file_get_args_t’ H5VL_DAOS_PRIVATE herr_t H5_daos_file_get(void *_item, H5VL_file_get_args_t *get_args, hid_t dxpl_id, ^ /home/mschaara/source/vol-daos/src/daos_vol.h:1147:60: error: unknown type name ‘H5VL_file_specific_args_t’ H5VL_DAOS_PRIVATE herr_t H5_daos_file_specific(void *item, H5VL_file_specific_args_t *specific_args, ^ ... `
> 
> Are you using the latest develop? H5VL_file_get_args_t, etc. were introduced a while ago in the develop branch.

no im using rc5.
but in this case, would it make sense to add some API version checking in this case to not break bwd compatibility?

**Comment by jhendersonHDF** [comment]
> > > I can't get this PR to build:
> > > `[ 1%] Building C object src/CMakeFiles/hdf5_vol_daos.dir/daos_vol.c.o In file included from /home/mschaara/source/vol-daos/src/daos_vol.c:16:0: /home/mschaara/source/vol-daos/src/daos_vol.h:1145:56: error: unknown type name ‘H5VL_file_get_args_t’ H5VL_DAOS_PRIVATE herr_t H5_daos_file_get(void *_item, H5VL_file_get_args_t *get_args, hid_t dxpl_id, ^ /home/mschaara/source/vol-daos/src/daos_vol.h:1147:60: error: unknown type name ‘H5VL_file_specific_args_t’ H5VL_DAOS_PRIVATE herr_t H5_daos_file_specific(void *item, H5VL_file_specific_args_t *specific_args, ^ ... `
> > 
> > 
> > Are you using the latest develop? H5VL_file_get_args_t, etc. were introduced a while ago in the develop branch.
> 
> no im using rc5. but in this case, would it make sense to add some API version checking in this case to not break bwd compatibility?

I think this is definitely a larger issue that THG needs to discuss, but the current line of thought for other VOLs seemed to be that supporting a VOL between both 1.12 and 1.13 would be non-trivial with the way that the VOL interface changed in 1.13. While it's certainly doable, it would definitely be messy with the removal of va_list processing in 1.13.

**Comment by mchaarawi** [comment]
> ce changed in 1.13. While it's certainly doable, it would definitely be messy with the removal of va_list processing in 1.13.

well im not speaking about 1.12 even. this doesn't work with 1.13-rc5!
normally anytime you do an API addition, that requires a minor version bump that lets you check for it at build time for tools and libraries using HDF5 like the VOL. If an API is changed or removed, that would be a major version bump, but i assume this case is the former.
anyway with this change, we cannot update the VOL anymore in our CI, until we have an HDF5 version release or release candidate that we would have to update to. in any case, it sounds like RC has been misleading term here for 1.13 as API changes should be finalized before an RC :-/

**Comment by jhendersonHDF** [comment]
> > ce changed in 1.13. While it's certainly doable, it would definitely be messy with the removal of va_list processing in 1.13.
> 
> well im not speaking about 1.12 even. this doesn't work with 1.13-rc5! normally anytime you do an API addition, that requires a minor version bump that lets you check for it at build time for tools and libraries using HDF5 like the VOL. If an API is changed or removed, that would be a major version bump, but i assume this case is the former. anyway with this change, we cannot update the VOL anymore in our CI, until we have an HDF5 version release or release candidate that we would have to update to. in any case, it sounds like RC has been misleading term here for 1.13 as API changes should be finalized before an RC :-/

Updating the DAOS VOL to be compatible with the current develop branch was one of the last blockers for being able to release 1.13, in which case you'd be able to use that in your CI, but I don't really have any idea on the timeline for the release. @epourmal would probably be better for addressing that, as well as the breaking changes between RCs, but since this is a breaking API change, I think it's perfectly reasonable not to merge the PR until 1.13 has actually been released. I can just maintain it in the meantime.

File: src/daos_vol_file.c (hunk 2 above)
Comment (jhendersonHDF) [reply src/daos_vol_file.c]: Sshould be fixed now

**Comment by mchaarawi** [comment]
does the VOL without this change here work with latest hdf5 develop?

**Comment by jhendersonHDF** [comment]
Since the signature for various VOL callbacks changed in develop, the current VOL would also have issues building as well.

**Review by fortnern — APPROVED** [review]
